'use client';

import Image from 'next/image';
import { Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { useCart } from './CartContext';
import { formatCartPrice } from './cartUtils';

export default function CartPage() {
  const { items, subtotalCents, updateQuantity, removeItem } = useCart();
  if (!items.length) return <section className="section flex min-h-[60vh] flex-col items-center justify-center text-center"><ShoppingBag size={42} className="text-brand"/><p className="eyebrow mt-6">Seu carrinho</p><h1 className="section-title">SEU CARRINHO ESTÁ <span className="text-brand">VAZIO.</span></h1><p className="mt-5 max-w-md leading-7 text-zinc-400">Explore a coleção e escolha os próximos destaques do seu visual.</p><a href="/produtos" className="button-primary mt-8">Continuar comprando</a></section>;
  return <section className="section"><p className="eyebrow">Seu pedido</p><h1 className="section-title">CARRINHO DE <span className="text-brand">COMPRAS.</span></h1><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_360px] lg:items-start"><ul className="divide-y divide-white/10 rounded-2xl border border-white/10 bg-white/[.025] px-5 sm:px-7">{items.map((item) => <li key={item.key} className="flex gap-4 py-5 sm:gap-6"><div className="relative h-28 w-24 shrink-0 overflow-hidden rounded-xl bg-zinc-900"><Image src={item.image} alt={item.name} fill sizes="96px" className="object-contain"/></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold sm:text-lg">{item.name}</h2>{(item.selectedSize || item.selectedColor) && <p className="mt-1 text-xs text-zinc-500">{[item.selectedSize && `Tamanho: ${item.selectedSize}`, item.selectedColor && `Cor: ${item.selectedColor}`].filter(Boolean).join(' · ')}</p>}</div><button type="button" onClick={() => removeItem(item.key)} aria-label={`Remover ${item.name}`} className="p-1 text-zinc-500 transition hover:text-red-400"><Trash2 size={17}/></button></div><p className="mt-3 font-extrabold text-brand">{formatCartPrice(item.price_cents)}</p><div className="mt-4 flex items-center justify-between"><div className="flex items-center rounded-lg border border-white/15"><button type="button" onClick={() => updateQuantity(item.key, item.quantity - 1)} aria-label={`Diminuir quantidade de ${item.name}`} className="grid h-9 w-9 place-items-center hover:text-brand"><Minus size={14}/></button><span className="w-8 text-center text-sm font-bold">{item.quantity}</span><button type="button" onClick={() => updateQuantity(item.key, item.quantity + 1)} aria-label={`Aumentar quantidade de ${item.name}`} className="grid h-9 w-9 place-items-center hover:text-brand"><Plus size={14}/></button></div><strong className="text-sm">{formatCartPrice(item.price_cents * item.quantity)}</strong></div></div></li>)}</ul><aside className="rounded-2xl border border-white/10 bg-white/[.04] p-6 lg:sticky lg:top-24"><h2 className="text-lg font-extrabold">RESUMO DO PEDIDO</h2><div className="mt-6 flex items-center justify-between border-y border-white/10 py-5"><span className="text-sm text-zinc-400">Subtotal</span><strong className="text-xl text-brand">{formatCartPrice(subtotalCents)}</strong></div><a href="/checkout" className="button-primary mt-6 w-full">Finalizar compra</a><a href="/produtos" className="button-dark mt-3 w-full">Continuar comprando</a></aside></div></section>;
}
