'use client';

import { LoaderCircle, LogIn } from 'lucide-react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useState } from 'react';
import { createClient } from '../../../lib/supabase/client';

export default function LoginForm() {
  const router = useRouter(); const params = useSearchParams(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(params.get('unauthorized') === '1' ? 'Esta conta não possui acesso administrativo.' : ''); const [loading, setLoading] = useState(false);
  async function submit(event) { event.preventDefault(); setError(''); setLoading(true); const supabase = createClient(); try { await supabase.auth.signOut(); const { error: signInError } = await supabase.auth.signInWithPassword({ email, password }); if (signInError) { setError('Não foi possível entrar. Confira seu e-mail e senha.'); return; } const { data: { user }, error: userError } = await supabase.auth.getUser(); if (userError || !user) { await supabase.auth.signOut(); setError('Não foi possível entrar. Confira seu e-mail e senha.'); return; } const { data: admin, error: adminError } = await supabase.from('admin_users').select('user_id').eq('user_id', user.id).maybeSingle(); if (adminError || !admin) { await supabase.auth.signOut(); setError('Esta conta não possui acesso administrativo.'); return; } const next = params.get('next'); const destination = next?.startsWith('/admin') && !next.startsWith('//') ? next : '/admin/dashboard'; router.replace(destination); router.refresh(); } catch { await supabase.auth.signOut(); setError('Não foi possível entrar. Confira seu e-mail e senha.'); } finally { setLoading(false); } }
  return <form onSubmit={submit} className="mt-8 space-y-5"><label className="block text-sm font-semibold text-zinc-200">E-mail<input required type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-black/40 px-4 py-3.5 text-white outline-none transition focus:border-brand focus:ring-2 focus:ring-brand/20" placeholder="voce@exemplo.com"/></label><label className="block text-sm font-semibold text-zinc-200">Senha<input required type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-black/40 px-4 py-3.5 text-white outline-none transition focus:border-brand focus:ring-2 focus:ring-brand/20" placeholder="Sua senha"/></label>{error && <p role="alert" className="rounded-lg border border-red-400/30 bg-red-400/10 px-4 py-3 text-sm text-red-200">{error}</p>}<button disabled={loading} type="submit" className="button-primary w-full disabled:cursor-not-allowed disabled:opacity-70">{loading ? <LoaderCircle size={17} className="animate-spin"/> : <LogIn size={17}/>} {loading ? 'Entrando...' : 'Entrar'}</button></form>;
}
