'use client';

import { Check, Edit3, LoaderCircle, MapPin, Plus, Trash2, UserRound } from 'lucide-react';
import { useState } from 'react';
import { changePassword, deleteAddress, saveAddress, saveProfile, setPrimaryAddress } from './actions';

const blankAddress = { apelido: '', destinatario: '', cep: '', rua: '', numero: '', complemento: '', bairro: '', cidade: '', estado: '', principal: false };

function Notice({ result }) {
  if (!result) return null;
  return <p role={result.error ? 'alert' : 'status'} className={`mt-4 rounded-lg border px-4 py-3 text-sm ${result.error ? 'border-red-400/30 bg-red-400/10 text-red-200' : 'border-brand/30 bg-brand/10 text-brand'}`}>{result.error || result.success}</p>;
}

export default function AccountManager({ user, profile, addresses }) {
  const [profileData, setProfileData] = useState(profile);
  const [profileResult, setProfileResult] = useState(null);
  const [passwordResult, setPasswordResult] = useState(null);
  const [addressResult, setAddressResult] = useState(null);
  const [editingAddress, setEditingAddress] = useState(null);
  const [saving, setSaving] = useState('');
  const input = 'mt-2 w-full rounded-xl border border-white/15 bg-black/40 px-4 py-3 text-white outline-none transition focus:border-brand focus:ring-2 focus:ring-brand/20';

  async function submitProfile(event) { event.preventDefault(); setSaving('profile'); const result = await saveProfile(new FormData(event.currentTarget)); setProfileResult(result); setSaving(''); }
  async function submitPassword(event) { event.preventDefault(); const form = event.currentTarget; setSaving('password'); try { const result = await changePassword(new FormData(form)); setPasswordResult(result); if (result.success) form.reset(); } finally { setSaving(''); } }
  async function submitAddress(event) { event.preventDefault(); setSaving('address'); const result = await saveAddress(new FormData(event.currentTarget)); setAddressResult(result); if (result.success) setEditingAddress(null); setSaving(''); }
  async function removeAddress(id) { if (!window.confirm('Excluir este endereço?')) return; setSaving(id); setAddressResult(await deleteAddress(id)); setSaving(''); }
  async function makePrimary(id) { setSaving(id); setAddressResult(await setPrimaryAddress(id)); setSaving(''); }

  return <section id="minha-conta" className="section scroll-mt-32 pt-12">
    <p className="eyebrow">Área do cliente</p><h1 className="section-title">MINHA <span className="text-brand">CONTA.</span></h1><p className="mt-4 text-sm text-zinc-400">{user.email}</p>
    <div className="mt-10 grid gap-7 lg:grid-cols-2">
      <form onSubmit={submitProfile} className="glass rounded-2xl p-6 sm:p-7"><div className="flex items-center gap-3"><UserRound className="text-brand" /><h2 className="text-lg font-extrabold">Meus dados</h2></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Nome<input required name="nome" value={profileData.nome || ''} onChange={(event) => setProfileData({ ...profileData, nome: event.target.value })} className={input} /></label><label className="text-sm font-semibold">Sobrenome<input required name="sobrenome" value={profileData.sobrenome || ''} onChange={(event) => setProfileData({ ...profileData, sobrenome: event.target.value })} className={input} /></label></div><label className="mt-4 block text-sm font-semibold">Telefone<input name="telefone" type="tel" value={profileData.telefone || ''} onChange={(event) => setProfileData({ ...profileData, telefone: event.target.value })} className={input} /></label><button disabled={saving === 'profile'} className="button-primary mt-6 w-full disabled:opacity-70">{saving === 'profile' && <LoaderCircle size={16} className="animate-spin" />}Salvar dados</button><Notice result={profileResult} /></form>
      <form onSubmit={submitPassword} className="glass rounded-2xl p-6 sm:p-7"><h2 className="text-lg font-extrabold">Alterar senha</h2><label className="mt-6 block text-sm font-semibold">Nova senha<input required name="password" type="password" autoComplete="new-password" className={input} /></label><label className="mt-4 block text-sm font-semibold">Confirmar nova senha<input required name="confirmation" type="password" autoComplete="new-password" className={input} /></label><button disabled={saving === 'password'} className="button-dark mt-6 w-full disabled:opacity-70">{saving === 'password' && <LoaderCircle size={16} className="animate-spin" />}Alterar senha</button><Notice result={passwordResult} /></form>
    </div>
    <section id="enderecos" className="mt-10 scroll-mt-32">
      <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">Endereços</p><h2 className="text-2xl font-extrabold">MEUS ENDEREÇOS</h2></div><button type="button" onClick={() => setEditingAddress(blankAddress)} className="button-primary"><Plus size={16} />Adicionar endereço</button></div><Notice result={addressResult} />
      {editingAddress && <form onSubmit={submitAddress} className="glass mt-6 rounded-2xl p-6 sm:p-7"><input type="hidden" name="id" value={editingAddress.id || ''} /><div className="flex items-center justify-between gap-5"><h3 className="text-lg font-extrabold">{editingAddress.id ? 'Editar endereço' : 'Novo endereço'}</h3><button type="button" onClick={() => setEditingAddress(null)} className="text-sm text-zinc-400 hover:text-white">Cancelar</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[['apelido', 'Apelido'], ['destinatario', 'Destinatário'], ['cep', 'CEP'], ['rua', 'Rua'], ['numero', 'Número'], ['complemento', 'Complemento'], ['bairro', 'Bairro'], ['cidade', 'Cidade'], ['estado', 'Estado']].map(([key, label]) => <label key={key} className="text-sm font-semibold">{label}<input required={key !== 'complemento'} name={key} value={editingAddress[key] || ''} onChange={(event) => setEditingAddress({ ...editingAddress, [key]: event.target.value })} className={input} /></label>)}</div><label className="mt-5 flex items-center gap-3 text-sm font-semibold"><input name="principal" type="checkbox" checked={editingAddress.principal} onChange={(event) => setEditingAddress({ ...editingAddress, principal: event.target.checked })} className="h-4 w-4 accent-[#F5C518]" />Definir como endereço principal</label><button disabled={saving === 'address'} className="button-primary mt-6 disabled:opacity-70">{saving === 'address' && <LoaderCircle size={16} className="animate-spin" />}Salvar endereço</button></form>}
      <div className="mt-6 grid gap-4 md:grid-cols-2">{addresses.length ? addresses.map((address) => <article key={address.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><MapPin size={18} className="mt-1 text-brand" /><div><div className="flex flex-wrap gap-2"><h3 className="font-bold">{address.apelido}</h3>{address.principal && <span className="rounded-full bg-brand px-2 py-0.5 text-[10px] font-extrabold text-ink">PRINCIPAL</span>}</div><p className="mt-2 text-sm leading-6 text-zinc-400">{address.destinatario}<br />{address.rua}, {address.numero}{address.complemento ? ` - ${address.complemento}` : ''}<br />{address.bairro} · {address.cidade}/{address.estado}<br />CEP {address.cep}</p></div></div></div><div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={() => setEditingAddress(address)} className="text-sm font-bold text-brand"><Edit3 size={14} className="mr-1 inline" />Editar</button>{!address.principal && <button type="button" disabled={saving === address.id} onClick={() => makePrimary(address.id)} className="text-sm font-bold text-zinc-300 hover:text-brand"><Check size={14} className="mr-1 inline" />Tornar principal</button>}<button type="button" disabled={saving === address.id} onClick={() => removeAddress(address.id)} className="text-sm font-bold text-zinc-500 hover:text-red-400"><Trash2 size={14} className="mr-1 inline" />Excluir</button></div></article>) : <p className="rounded-2xl border border-dashed border-white/15 p-7 text-sm text-zinc-500">Você ainda não cadastrou nenhum endereço.</p>}</div>
    </section>
  </section>;
}
