'use client';
import { Copy, LoaderCircle, Upload } from 'lucide-react';
import { useState } from 'react';
import { uploadPaymentProof } from '../../app/pedido-confirmado/[id]/actions';
const labels = { pendente: 'Pagamento pendente', aguardando_confirmacao: 'Aguardando confirmação', pago: 'Pago', recusado: 'Comprovante recusado' };
export default function PixPaymentPanel({ order, settings }) {
  const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  const canUpload = order.payment_status !== 'pago';
  async function copy() { try { await navigator.clipboard.writeText(settings.pixKey || ''); setMessage('Chave PIX copiada.'); } catch { setMessage('Não foi possível copiar a chave PIX.'); } }
  async function submit(event) { event.preventDefault(); const form = event.currentTarget; setLoading(true); setMessage(''); const result = await uploadPaymentProof(new FormData(form)); setMessage(result.error || result.success); if (result.success) form.reset(); setLoading(false); }
  return <section className="rounded-2xl border border-brand/30 bg-brand/[.06] p-6 text-left"><p className="eyebrow">Pagamento PIX</p><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><strong className="text-lg">{labels[order.payment_status] || 'Pagamento pendente'}</strong><span className="rounded-full border border-brand/30 px-3 py-1 text-xs font-bold text-brand">{settings.pixKeyType || 'PIX'}</span></div>{settings.pixKey ? <><p className="mt-5 text-xs uppercase tracking-wider text-zinc-500">Chave PIX</p><p className="mt-1 break-all font-bold text-white">{settings.pixKey}</p><button type="button" onClick={copy} className="button-dark mt-3 px-4 py-2 text-xs"><Copy size={14}/>Copiar chave PIX</button><p className="mt-5 text-sm text-zinc-300">{settings.pixReceiverName || settings.storeName}{settings.pixCity ? ` · ${settings.pixCity}` : ''}</p>{settings.pixInstructions && <p className="mt-2 text-sm leading-6 text-zinc-400">{settings.pixInstructions}</p>}</> : <p className="mt-4 text-sm text-zinc-400">Os dados PIX serão confirmados pela loja.</p>}{canUpload && <form onSubmit={submit} className="mt-6 border-t border-white/10 pt-5"><label className="grid gap-2 text-sm font-bold">Enviar comprovante<input name="file" required type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className="text-sm font-normal text-zinc-400"/></label><input type="hidden" name="orderId" value={order.id}/><p className="mt-2 text-xs text-zinc-500">JPG, PNG, WEBP ou PDF · até 5 MB.</p><button disabled={loading} className="button-primary mt-4 px-4 py-3 disabled:opacity-60">{loading ? <LoaderCircle size={16} className="animate-spin"/> : <Upload size={16}/>}Enviar comprovante</button></form>}{message && <p role="status" className="mt-4 text-sm text-brand">{message}</p>}</section>;
}
