'use client';
import { LoaderCircle, MessageCircle, RotateCcw } from 'lucide-react';
import { useState } from 'react';
import { useCart } from '../../../../components/cart/CartContext';
import { formatCartPrice } from '../../../../components/cart/cartUtils';
import PixPaymentPanel from '../../../../components/orders/PixPaymentPanel';
import ShippingSummary from '../../../../components/orders/ShippingSummary';
const labels = { novo: 'Novo', confirmado: 'Confirmado', em_preparo: 'Em preparo', pronto_para_envio: 'Pronto para envio', enviado: 'Enviado', saiu_para_entrega: 'Saiu para entrega', entregue: 'Entregue', cancelado: 'Cancelado' };
export default function OrderDetails({ order, address, settings, products }) {
  const { addItem } = useCart(); const [message, setMessage] = useState(''); const [adding, setAdding] = useState(false);
  function buyAgain() { setAdding(true); const available = new Map(products.filter((p) => p.productId).map((p) => [p.productId, p])); let count = 0; for (const item of order.order_items || []) { const p = available.get(item.product_id); if (p) { addItem(p, { selectedSize: item.size || '', selectedColor: item.color || '', quantity: item.quantity }); count += 1; } } setMessage(count ? `${count} item(ns) adicionado(s) ao carrinho.` : 'Nenhum item continua disponível.'); setAdding(false); }
  return <section className="section pt-12"><p className="eyebrow">Meus pedidos</p><h1 className="section-title">PEDIDO <span className="text-brand">#{order.order_number}</span></h1><span className="mt-4 inline-block rounded-full border border-brand/30 bg-brand/10 px-3 py-1 text-sm font-bold text-brand">{labels[order.status] || order.status}</span><div className="mt-10 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-6"><section className="glass rounded-2xl p-6"><h2 className="text-lg font-extrabold">ITENS</h2>{(order.order_items || []).map((item) => <div key={item.id} className="mt-4 flex justify-between border-t border-white/10 pt-3"><div><strong>{item.product_name}</strong><p className="text-sm text-zinc-500">{item.quantity}x · {[item.size && `Tam. ${item.size}`, item.color && `Cor ${item.color}`].filter(Boolean).join(' · ')}</p></div><strong className="text-brand">{formatCartPrice(item.subtotal)}</strong></div>)}</section><ShippingSummary order={order} address={address}/>{order.payment_method === 'pix' && <PixPaymentPanel order={order} settings={settings}/>}</div><aside className="glass h-fit rounded-2xl p-6"><h2 className="text-lg font-extrabold">TOTAIS</h2><p className="mt-4 text-sm">Subtotal <strong className="float-right">{formatCartPrice(order.subtotal)}</strong></p><p className="mt-3 text-sm">Frete <strong className="float-right">{formatCartPrice(order.shipping)}</strong></p><p className="mt-4 border-t border-white/10 pt-4">Total <strong className="float-right text-brand">{formatCartPrice(order.total)}</strong></p><button type="button" disabled={adding} onClick={buyAgain} className="button-primary mt-7 w-full disabled:opacity-70">{adding ? <LoaderCircle size={16} className="animate-spin"/> : <RotateCcw size={16}/>}Comprar novamente</button><a href={`https://wa.me/${settings.whatsapp}`} target="_blank" rel="noreferrer" className="button-dark mt-3 w-full"><MessageCircle size={16}/>WhatsApp</a>{message && <p role="status" className="mt-4 text-sm text-brand">{message}</p>}</aside></div></section>;
}
