'use client';

import { ArrowUpRight, Menu, ShoppingBag, X } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import Image from 'next/image';
import { useEffect, useState } from 'react';

const desktopLinks = [['Início', '/'], ['Produtos', '/produtos'], ['Categorias', '/#categorias'], ['Sobre', '/#sobre'], ['Contato', '/#contato']];
const mobileLinks = [['Início', '/'], ['Produtos', '/produtos'], ['Masculino', '/produtos?categoria=masculino'], ['Feminino', '/produtos?categoria=feminino'], ['Calçados', '/produtos?categoria=tenis'], ['Acessórios', '/produtos?categoria=acessorios'], ['Contato', '/#contato']];

export default function Header({ settings }) {
  const [open, setOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 28); onScroll(); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll); }, []);
  useEffect(() => { document.body.style.overflow = open ? 'hidden' : ''; return () => { document.body.style.overflow = ''; }; }, [open]);

  return <header className={`fixed inset-x-0 top-0 z-50 transition-all duration-500 ${scrolled ? 'bg-ink/95 shadow-[0_8px_30px_rgba(0,0,0,.22)] backdrop-blur-xl' : 'bg-transparent'}`}><div className={`mx-auto flex h-[78px] max-w-7xl items-center justify-between px-5 transition-colors sm:px-8 lg:px-12 ${scrolled ? 'border-b border-white/10' : ''}`}><a href="/" className="text-[1.35rem] font-extrabold tracking-[.08em] sm:text-[1.45rem]">{settings?.logoUrl ? <Image src={settings.logoUrl} alt={settings.storeName || 'Bros Store'} width={220} height={52} sizes="220px" className="h-10 w-auto object-contain" /> : <>BROS<span className="ml-1 text-brand">STORE</span></>}</a><nav aria-label="Navegação principal" className="hidden items-center gap-8 lg:flex">{desktopLinks.map(([name, href]) => <a key={href} href={href} className="text-[11px] font-bold uppercase tracking-[.12em] text-zinc-300 transition hover:text-brand">{name}</a>)}</nav><div className="flex items-center gap-3"><a className="hidden items-center gap-2 text-[11px] font-bold uppercase tracking-wider text-brand sm:flex" href="/produtos">Comprar agora <ArrowUpRight size={14}/></a><a aria-label="Produtos" className="grid h-10 w-10 place-items-center rounded-lg border border-white/15 transition hover:border-brand" href="/produtos"><ShoppingBag size={17}/></a><button type="button" aria-label={open ? 'Fechar menu' : 'Abrir menu'} onClick={() => setOpen((value) => !value)} className="relative z-[60] grid h-10 w-10 place-items-center rounded-lg border border-white/15 lg:hidden">{open ? <X size={20}/> : <Menu size={20}/>}</button></div></div><AnimatePresence>{open && <motion.div initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} transition={{ duration: .45, ease: [0.22, 1, .36, 1] }} className="fixed inset-y-0 right-0 z-50 flex w-full max-w-md flex-col bg-ink px-7 pb-8 pt-28 shadow-[-30px_0_80px_rgba(0,0,0,.5)] sm:px-10"><p className="eyebrow">Navegue pela Bros</p><nav className="flex flex-1 flex-col justify-center gap-1">{mobileLinks.map(([name, href], index) => <motion.a initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .13 + index * .055 }} onClick={() => setOpen(false)} href={href} key={name} className="border-b border-white/10 py-4 text-3xl font-extrabold tracking-tight transition hover:pl-2 hover:text-brand">{name}</motion.a>)}</nav><div className="flex items-center justify-between border-t border-white/10 pt-6 text-xs text-zinc-500"><span>{settings?.slogan || 'Vista sua atitude.'}</span><span className="text-brand">{settings?.storeName || 'Bros Store'}</span></div></motion.div>}</AnimatePresence></header>;
}
