'use client';
import { ChevronDown, Camera, Mail, MapPin, Send, Star } from 'lucide-react';
import { useState } from 'react';
import { siteConfig, whatsappLink } from '../lib/siteConfig';

// Depoimentos de exemplo — substitua pelos comentários reais dos seus clientes
// antes de publicar (nome, foto/print ou avaliação de fontes como Google/Instagram).
const shots = ['https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1496217590455-aa63a8350eea?auto=format&fit=crop&w=900&q=85'];
const reviews = [['“A experiência é impecável, desde a embalagem até a qualidade das peças. A Bros tem identidade.”', 'Caio A.', 'Cliente Bros'], ['“Meu tênis chegou muito rápido e é ainda mais bonito ao vivo. Já virei cliente fiel.”', 'Larissa M.', 'Cliente verificada'], ['“O atendimento pelo WhatsApp foi direto e muito atencioso. Curadoria incrível.”', 'Rafael B.', 'Cliente verificado']];
const faqs = [['Como acompanho meu pedido?', 'Depois da confirmação, enviamos o código de rastreio diretamente pelo WhatsApp cadastrado.'], ['Quais são as formas de pagamento?', 'Aceitamos Pix, cartão de crédito e parcelamento em até 6x sem juros.'], ['Posso trocar um produto?', 'Sim. Você pode solicitar a troca em até 7 dias corridos após o recebimento.'], ['As peças são originais?', 'Sempre. Nossa curadoria trabalha apenas com fornecedores e materiais confiáveis.']];

export function Gallery() { return <section className="section"><div className="mb-10 flex items-end justify-between"><div><p className="eyebrow">Estilo Bros</p><h2 className="section-title">A ATITUDE<br/><span className="text-brand">EM MOVIMENTO.</span></h2></div><a href={siteConfig.instagramUrl} target="_blank" rel="noreferrer" className="hidden items-center gap-2 text-xs font-bold uppercase tracking-wider text-brand sm:flex"><Camera size={16}/> {siteConfig.instagramHandle}</a></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{shots.map((src,i)=><a key={src} href={siteConfig.instagramUrl} target="_blank" rel="noreferrer" className={`group relative overflow-hidden ${i===0?'col-span-2 row-span-2 aspect-square':'aspect-square'}`}><img src={src} alt={`Editorial Bros Store ${i+1}`} className="h-full w-full object-cover transition duration-700 group-hover:scale-110 group-hover:brightness-75"/><span className="absolute inset-0 grid place-items-center opacity-0 transition group-hover:opacity-100"><Camera className="text-brand"/></span></a>)}</div></section>; }

export function Benefits() { const items = ['Produtos selecionados', 'Qualidade garantida', 'Atendimento personalizado', 'Entrega para todo o Brasil']; return <section className="border-y border-white/10 bg-charcoal"><div className="section grid gap-6 py-10 sm:grid-cols-2 lg:grid-cols-4">{items.map((item, i) => <div key={item} className="flex items-center gap-4"><span className="grid h-9 w-9 shrink-0 place-items-center border border-brand/50 font-mono text-[10px] text-brand">0{i + 1}</span><p className="text-sm font-bold">{item}</p></div>)}</div></section>; }

export function SocialProof() { return <><section className="border-y border-white/10 bg-charcoal py-7 overflow-hidden"><div className="flex w-max animate-[scroll_25s_linear_infinite] gap-14 font-mono text-xs font-bold uppercase tracking-[.18em] text-zinc-500">{[...Array(2)].flatMap(()=>['NIKE','ADIDAS','NEW ERA','VANS','PUMA','OAKLEY','NIKE','ADIDAS','NEW ERA','VANS','PUMA','OAKLEY']).map((x,i)=><span key={i} className="flex items-center gap-14">{x}<b className="text-brand">✦</b></span>)}</div></section><section className="section"><p className="eyebrow">Quem veste, recomenda</p><h2 className="section-title">QUEM VESTE BROS<br/><span className="text-brand">RECOMENDA.</span></h2><div className="mt-11 grid gap-3 lg:grid-cols-3">{reviews.map(([quote,name,role])=><article className="glass p-7" key={name}><div className="flex text-brand">{[1,2,3,4,5].map(x=><Star key={x} size={14} fill="currentColor"/>)}</div><p className="mt-6 text-lg font-semibold leading-7 text-zinc-200">{quote}</p><div className="mt-8 border-t border-white/10 pt-4"><b className="text-sm">{name}</b><span className="ml-2 text-xs text-zinc-500">{role}</span></div></article>)}</div></section></>; }

export function FAQ() { const [active,setActive]=useState(null); return <section className="bg-[#0e0e0e]"><div className="section grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Sem mistério</p><h2 className="section-title">PERGUNTAS<br/>FREQUENTES.</h2><p className="mt-5 max-w-sm text-sm leading-6 text-zinc-500">Ainda precisa de ajuda? Nosso atendimento está pronto para você.</p></div><div className="border-t border-white/15">{faqs.map(([q,a],i)=><div className="border-b border-white/15" key={q}><button onClick={()=>setActive(active===i?null:i)} className="flex w-full items-center justify-between py-6 text-left text-sm font-bold"><span>{q}</span><ChevronDown size={19} className={`shrink-0 text-brand transition ${active===i?'rotate-180':''}`}/></button>{active===i&&<p className="-mt-2 max-w-xl pb-6 text-sm leading-6 text-zinc-400">{a}</p>}</div>)}</div></div></section>; }

export function ContactPremium() {
  const [form, setForm] = useState({ name: '', email: '', message: '' });
  const [sent, setSent] = useState(false);

  function handleChange(field) {
    return (event) => setForm((prev) => ({ ...prev, [field]: event.target.value }));
  }

  function handleSubmit(event) {
    event.preventDefault();
    const message = `Olá! Meu nome é ${form.name} (${form.email}).\n${form.message}`;
    window.open(whatsappLink(message), '_blank', 'noopener,noreferrer');
    setSent(true);
    setForm({ name: '', email: '', message: '' });
  }

  return <section id="contato" className="relative overflow-hidden bg-brand text-ink"><div className="absolute right-0 top-0 select-none text-[18rem] font-black leading-none text-black/[.06] sm:text-[26rem]">B</div><div className="section relative grid gap-14 py-20 lg:grid-cols-2"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.2em]">{siteConfig.name}</p><h2 className="mt-4 text-5xl font-extrabold leading-[.9] tracking-tight sm:text-6xl">VISTA SUA<br/>ATITUDE.</h2><p className="mt-5 max-w-sm text-base font-medium">Descubra uma nova forma de vestir sua personalidade.</p><div className="mt-10 grid gap-4 text-sm font-semibold"><a className="flex items-center gap-3" href={`mailto:${siteConfig.email}`}><Mail size={18}/> {siteConfig.email}</a><span className="flex items-center gap-3"><MapPin size={18}/> {siteConfig.address.full}</span></div></div><form onSubmit={handleSubmit} className="grid gap-4"><input required value={form.name} onChange={handleChange('name')} aria-label="Nome" placeholder="SEU NOME" className="border-b border-ink/35 bg-transparent px-0 py-4 text-sm font-bold placeholder:text-ink/60 outline-none"/><input required type="email" value={form.email} onChange={handleChange('email')} aria-label="E-mail" placeholder="SEU E-MAIL" className="border-b border-ink/35 bg-transparent px-0 py-4 text-sm font-bold placeholder:text-ink/60 outline-none"/><textarea required value={form.message} onChange={handleChange('message')} aria-label="Mensagem" placeholder="COMO PODEMOS AJUDAR?" rows="3" className="resize-none border-b border-ink/35 bg-transparent px-0 py-4 text-sm font-bold placeholder:text-ink/60 outline-none"/><button className="mt-3 inline-flex w-fit items-center gap-2 bg-ink px-6 py-4 text-xs font-extrabold uppercase tracking-[.12em] text-white transition hover:bg-zinc-800">Comprar agora <Send size={15}/></button>{sent && <p className="text-xs font-bold text-ink/80">Perfeito! Abrimos o WhatsApp para você concluir o contato.</p>}</form></div><iframe title={`Mapa ${siteConfig.name}`} className="h-64 w-full border-0 grayscale contrast-125" loading="lazy" src={`https://www.google.com/maps?q=${encodeURIComponent(siteConfig.address.mapsQuery)}&output=embed`}/></section>;
}
