import { Clock3, MapPin, PackageSearch, Truck } from 'lucide-react';
import { notFound, redirect } from 'next/navigation';
import { formatCartPrice } from '../../../../components/cart/cartUtils';
import { getAdminOrderDetails, isAdmin } from '../../../../lib/orders';
import { createClient } from '../../../../lib/supabase/server';
import OrderStatusForm from '../OrderStatusForm';
import PaymentActions from '../PaymentActions';
import ShippingManager from '../ShippingManager';

export const metadata = { title: 'Detalhes do pedido | Painel Bros Store', robots: { index: false, follow: false } };
const payments = { pix: 'Pix', dinheiro: 'Dinheiro', cartao_na_entrega: 'Cartão na entrega', mercado_pago_pix: 'Mercado Pago · Pix', mercado_pago_cartao: 'Mercado Pago · Cartão' };
const paymentLabels = { pendente: 'Pagamento pendente', aguardando_confirmacao: 'Aguardando confirmação', pago: 'Pago', recusado: 'Comprovante recusado', aguardando_pagamento: 'Aguardando pagamento', processando: 'Processando', aprovado: 'Aprovado', cancelado: 'Cancelado', reembolsado: 'Reembolsado' };
const logisticsLabels = { confirmado: 'Confirmado', em_preparacao: 'Em preparação', pronto_para_envio: 'Pronto para envio', enviado: 'Enviado', entregue: 'Entregue', cancelado: 'Cancelado' };
const labelLabels = { nao_solicitada: 'Não solicitada', carrinho_criado: 'Preparada no carrinho', comprando: 'Compra em andamento', comprada: 'Comprada', gerada: 'Gerada', falhou: 'Requer nova tentativa' };
function normalizedProofPath(path) { return String(path || '').replace(/^payment-proofs\//, '').replace(/^\/+/, ''); }
function estimate(order) { const min = order.shipping_estimated_days_min; const max = order.shipping_estimated_days_max; if (!min && !max) return 'Prazo não informado'; return min === max ? `${min} dia(s) útil(eis)` : `${min || max}–${max || min} dias úteis`; }

export default async function AdminOrderDetailPage({ params }) {
  const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect(`/admin/login?next=/admin/pedidos/${params.id}`);
  if (!await isAdmin(supabase, user.id)) redirect(`/admin/login?next=/admin/pedidos/${params.id}&unauthorized=1`);
  const order = await getAdminOrderDetails(params.id); if (!order) notFound();
  const shipment = Array.isArray(order.shipments) ? order.shipments[0] : order.shipments || null;
  const events = [...(shipment?.shipment_events || [])].sort((a, b) => new Date(b.occurred_at) - new Date(a.occurred_at));
  let proofUrl = null; let proofError = null; const proofPath = normalizedProofPath(order.payment_proof_path);
  if (order.payment_method === 'pix' && proofPath) {
    const { data, error } = await supabase.storage.from('payment-proofs').createSignedUrl(proofPath, 300);
    if (error || !data?.signedUrl) { console.error('[pix] signed proof URL failed', { code: error?.statusCode || error?.code }); proofError = 'Não foi possível abrir o comprovante agora.'; } else proofUrl = data.signedUrl;
  }
  const fileName = proofPath ? proofPath.split('/').pop() : null;
  const isMelhorEnvio = order.shipping_provider === 'melhor_envio';
  return <main className="min-h-screen bg-ink px-5 py-8 text-white sm:px-8 lg:px-12"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-5 border-b border-white/10 pb-7"><div><a href="/admin/dashboard" className="text-xl font-extrabold tracking-[.08em]">BROS<span className="ml-1 text-brand">STORE</span></a><p className="mt-2 text-sm text-zinc-400">Painel administrativo / Pedido #{order.order_number}</p></div><a href="/admin/pedidos" className="button-dark">Voltar aos pedidos</a></header>
    <section className="py-10"><p className="eyebrow">Pedido #{order.order_number}</p><h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl">DETALHES DO <span className="text-brand">PEDIDO.</span></h1>
      <div className="mt-8 rounded-2xl border border-white/10 bg-white/[.03] p-6"><p className="text-sm font-bold text-zinc-300">Atualizar status operacional</p><p className="mt-1 text-xs text-zinc-500">Postagem e entrega do Melhor Envio são confirmadas pela sincronização do provedor.</p><div className="mt-4"><OrderStatusForm id={order.id} currentStatus={order.status}/></div></div>
      <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="glass rounded-2xl p-6"><p className="eyebrow">Cliente e entrega</p><h2 className="text-xl font-extrabold">{order.customer ? `${order.customer.nome} ${order.customer.sobrenome}`.trim() : 'Cliente não identificado'}</h2><p className="mt-3 text-sm text-zinc-400">{order.customer?.telefone || 'Telefone não informado'}</p><div className="mt-5 flex gap-3 text-sm text-zinc-400"><MapPin size={18} className="shrink-0 text-brand"/><p>{order.address ? <>{order.address.rua}, {order.address.numero}{order.address.complemento ? ` · ${order.address.complemento}` : ''}<br/>{order.address.bairro} · {order.address.cidade}/{order.address.estado}<br/>CEP {order.address.cep}</> : 'Endereço indisponível.'}</p></div></section>
        <section className="glass rounded-2xl p-6"><p className="eyebrow">Pagamento</p><h2 className="text-xl font-extrabold">{payments[order.payment_method] || order.payment_method}</h2><p className="mt-4 text-sm font-bold text-brand">{paymentLabels[order.payment_status] || order.payment_status}</p>{order.payment_method === 'pix' && <>{order.payment_proof_uploaded_at && <p className="mt-2 text-sm text-zinc-400">Enviado em {new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(order.payment_proof_uploaded_at))}</p>}{fileName && <p className="mt-2 break-all text-xs text-zinc-500">Arquivo: {fileName}</p>}{proofUrl && <a href={proofUrl} target="_blank" rel="noreferrer" className="button-dark mt-4 px-4 py-3 text-sm">Visualizar comprovante</a>}{proofError && <p role="alert" className="mt-4 text-sm text-red-300">{proofError}</p>}{order.payment_proof_path && order.payment_status !== 'pago' && <PaymentActions orderId={order.id}/>}</>}</section>
      </div>
      <section className="mt-8 rounded-2xl border border-brand/20 bg-brand/[.04] p-6"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="eyebrow">Operação logística</p><h2 className="text-2xl font-extrabold">{order.shipping_service_name || 'Entrega não configurada'}</h2></div><span className="rounded-full border border-brand/30 bg-brand/10 px-3 py-1 text-xs font-bold text-brand">{logisticsLabels[shipment?.logistics_status] || logisticsLabels[order.status] || order.status}</span></div>
        <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs uppercase tracking-wider text-zinc-500">Provedor</p><p className="mt-1 font-bold">{isMelhorEnvio ? 'Melhor Envio' : order.shipping_provider || 'Manual'}</p></div><div><p className="text-xs uppercase tracking-wider text-zinc-500">Transportadora</p><p className="mt-1 font-bold">{shipment?.carrier || order.shipping_quote_metadata?.company || 'Não informada'}</p></div><div><p className="text-xs uppercase tracking-wider text-zinc-500">Frete</p><p className="mt-1 font-bold text-brand">{formatCartPrice(order.shipping || 0)}</p></div><div><p className="text-xs uppercase tracking-wider text-zinc-500">Prazo estimado</p><p className="mt-1 font-bold">{estimate(order)}</p></div></div>
        {isMelhorEnvio && <div className="mt-6 grid gap-6 border-t border-white/10 pt-6 lg:grid-cols-[1fr_300px]"><div className="grid gap-3 text-sm text-zinc-400"><p className="flex items-center gap-2"><PackageSearch size={17} className="text-brand"/>Etiqueta: <strong className="text-white">{labelLabels[shipment?.label_status] || 'Não preparada'}</strong></p><p className="flex items-center gap-2"><Truck size={17} className="text-brand"/>Rastreio: <strong className="text-white">{shipment?.tracking_code || 'Aguardando postagem'}</strong></p><p className="flex items-center gap-2"><Clock3 size={17} className="text-brand"/>Última sincronização: <strong className="text-white">{shipment?.tracking_last_synced_at ? new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(shipment.tracking_last_synced_at)) : 'Ainda não sincronizado'}</strong></p><p className="text-xs">Antes da compra: {shipment?.carrier || order.shipping_quote_metadata?.company || 'transportadora não informada'} · {order.shipping_service_name} · {formatCartPrice(order.shipping || 0)}.</p></div><ShippingManager orderId={order.id} shipment={shipment} canPrepare={!shipment?.external_order_id} canPurchase={['carrinho_criado','falhou','comprada'].includes(shipment?.label_status)}/></div>}
        {events.length > 0 && <div className="mt-6 border-t border-white/10 pt-5"><h3 className="text-sm font-extrabold">Histórico logístico</h3><ol className="mt-3 grid gap-3">{events.slice(0,10).map(event=><li key={event.id} className="flex justify-between gap-4 text-sm"><span>{event.description || event.status}</span><time className="shrink-0 text-zinc-500">{new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(event.occurred_at))}</time></li>)}</ol></div>}
      </section>
      <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><p className="eyebrow">Itens</p>{(order.order_items||[]).map(item=><div key={item.id} className="mt-4 flex justify-between border-t border-white/10 pt-3"><span>{item.product_name} · {item.quantity}x</span><strong className="text-brand">{formatCartPrice(item.subtotal)}</strong></div>)}</section><aside className="glass rounded-2xl p-6"><p className="eyebrow">Financeiro</p><p className="mt-3 text-sm">Subtotal <strong className="float-right">{formatCartPrice(order.subtotal)}</strong></p><p className="mt-3 text-sm">Frete <strong className="float-right">{formatCartPrice(order.shipping)}</strong></p><p className="mt-4 border-t border-white/10 pt-4">Total <strong className="float-right text-brand">{formatCartPrice(order.total)}</strong></p></aside></div>
    </section></div></main>;
}
