'use client';

import { LoaderCircle, LogIn, Mail } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { createClient } from '../../lib/supabase/client';

export default function LoginForm() {
  const router = useRouter();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [recovery, setRecovery] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event) { event.preventDefault(); setError(''); setMessage(''); setLoading(true); try { const supabase = createClient(); if (recovery) { const { error: recoveryError } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/login` }); if (recoveryError) throw recoveryError; setMessage('Enviamos as instruções de recuperação para seu e-mail.'); return; } const { error: loginError } = await supabase.auth.signInWithPassword({ email, password }); if (loginError) throw loginError; router.replace('/minha-conta'); router.refresh(); } catch (submitError) { setError(recovery ? 'Não foi possível enviar as instruções. Confira o e-mail e tente novamente.' : 'Não foi possível entrar. Confira seu e-mail e senha.'); } finally { setLoading(false); } }
  return <form onSubmit={submit} className="mt-8 space-y-5"><label className="block text-sm font-semibold text-zinc-200">E-mail<input required type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-black/40 px-4 py-3.5 text-white outline-none transition focus:border-brand focus:ring-2 focus:ring-brand/20" placeholder="voce@exemplo.com" /></label>{!recovery && <label className="block text-sm font-semibold text-zinc-200">Senha<input required type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-black/40 px-4 py-3.5 text-white outline-none transition focus:border-brand focus:ring-2 focus:ring-brand/20" placeholder="Sua senha" /></label>}{error && <p role="alert" className="rounded-lg border border-red-400/30 bg-red-400/10 px-4 py-3 text-sm text-red-200">{error}</p>}{message && <p role="status" className="rounded-lg border border-brand/30 bg-brand/10 px-4 py-3 text-sm text-brand">{message}</p>}<button disabled={loading} type="submit" className="button-primary w-full disabled:cursor-not-allowed disabled:opacity-70">{loading ? <LoaderCircle size={17} className="animate-spin"/> : recovery ? <Mail size={17}/> : <LogIn size={17}/>} {loading ? 'Aguarde...' : recovery ? 'Enviar instruções' : 'Entrar'}</button><div className="flex items-center justify-between text-sm"><button type="button" onClick={() => { setRecovery(!recovery); setError(''); setMessage(''); }} className="text-zinc-400 transition hover:text-brand">{recovery ? 'Voltar ao login' : 'Esqueci minha senha'}</button>{!recovery && <a href="/cadastro" className="font-bold text-brand">Criar conta</a>}</div></form>;
}
