'use client';

import { LoaderCircle, UserPlus } from 'lucide-react';
import { useState } from 'react';
import { createClient } from '../../lib/supabase/client';

export default function SignupForm() {
  const [values, setValues] = useState({ nome: '', sobrenome: '', email: '', telefone: '', senha: '', confirmacao: '' }); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  const field = (name, label, type = 'text') => <label className="block text-sm font-semibold text-zinc-200">{label}<input required={name !== 'telefone'} type={type} autoComplete={name === 'email' ? 'email' : name === 'senha' ? 'new-password' : undefined} value={values[name]} onChange={(event) => setValues({ ...values, [name]: event.target.value })} className="mt-2 w-full rounded-xl border border-white/15 bg-black/40 px-4 py-3.5 text-white outline-none transition focus:border-brand focus:ring-2 focus:ring-brand/20" /></label>;
  async function submit(event) { event.preventDefault(); setError(''); setMessage(''); if (values.senha.length < 6) { setError('A senha precisa ter ao menos 6 caracteres.'); return; } if (values.senha !== values.confirmacao) { setError('A confirmação de senha não confere.'); return; } setLoading(true); try { const supabase = createClient(); const { data, error: signupError } = await supabase.auth.signUp({ email: values.email, password: values.senha, options: { data: { nome: values.nome, sobrenome: values.sobrenome, telefone: values.telefone } } }); if (signupError) throw signupError; setMessage(data.session ? 'Conta criada com sucesso. Você já pode acessar sua área.' : 'Conta criada. Verifique seu e-mail para confirmar o cadastro.'); } catch { setError('Não foi possível criar sua conta. Tente novamente com outro e-mail.'); } finally { setLoading(false); } }
  return <form onSubmit={submit} className="mt-8 space-y-5"><div className="grid gap-5 sm:grid-cols-2">{field('nome', 'Nome')}{field('sobrenome', 'Sobrenome')}</div>{field('email', 'E-mail', 'email')}{field('telefone', 'Telefone', 'tel')}{field('senha', 'Senha', 'password')}{field('confirmacao', 'Confirmar senha', 'password')}{error && <p role="alert" className="rounded-lg border border-red-400/30 bg-red-400/10 px-4 py-3 text-sm text-red-200">{error}</p>}{message && <p role="status" className="rounded-lg border border-brand/30 bg-brand/10 px-4 py-3 text-sm text-brand">{message}</p>}<button disabled={loading} type="submit" className="button-primary w-full disabled:cursor-not-allowed disabled:opacity-70">{loading ? <LoaderCircle size={17} className="animate-spin"/> : <UserPlus size={17}/>} {loading ? 'Criando conta...' : 'Criar conta'}</button><p className="text-center text-sm text-zinc-400">Já possui conta? <a href="/login" className="font-bold text-brand">Entrar</a></p></form>;
}
