'use server';
import { revalidatePath } from 'next/cache';
import { createClient } from '../../../lib/supabase/server';

async function admin() { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error('Sessão expirada.'); const { data } = await supabase.from('admin_users').select('user_id').eq('user_id', user.id).maybeSingle(); if (!data) throw new Error('Sem permissão administrativa.'); return supabase; }
const slugify = (value) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
async function asset(supabase, file, label) { if (!(file instanceof File) || !file.size) return null; if (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024) throw new Error('Use JPG, PNG ou WEBP de até 5 MB.'); const ext = file.type.split('/')[1].replace('jpeg','jpg'); const path = `categories/${label}-${crypto.randomUUID()}.${ext}`; const { error } = await supabase.storage.from('product-images').upload(path, Buffer.from(await file.arrayBuffer()), { contentType: file.type }); if (error) throw new Error(error.message); return path; }
export async function saveCategory(formData) { try { const supabase = await admin(); const id = formData.get('id'); const name = String(formData.get('name') || '').trim(); const slug = slugify(String(formData.get('slug') || name)); if (!name || !slug) throw new Error('Informe nome e slug.'); const values = { name, slug, description: String(formData.get('description') || '').trim() || null, sort_order: Number(formData.get('sortOrder') || 0), is_active: formData.get('isActive') === 'on' }; const image = await asset(supabase, formData.get('image'), 'image'); const banner = await asset(supabase, formData.get('banner'), 'banner'); if (image) values.image_path = image; if (banner) values.banner_path = banner; let result; if (id) result = await supabase.from('categories').update(values).eq('id', id).select().maybeSingle(); else result = await supabase.from('categories').insert(values).select().maybeSingle(); if (result.error || !result.data) throw new Error(result.error?.code === '23505' ? 'Este slug já está em uso.' : result.error?.message || 'Não foi possível salvar a categoria.'); revalidatePath('/'); revalidatePath('/produtos'); revalidatePath('/admin/categorias'); return { success: true }; } catch (error) { return { error: error.message || 'Não foi possível salvar.' }; } }
export async function toggleCategory(id, active) { try { const supabase = await admin(); const { data, error } = await supabase.from('categories').update({ is_active: active }).eq('id', id).select('id').maybeSingle(); if (error || !data) throw new Error(error?.message || 'Categoria não encontrada.'); revalidatePath('/'); revalidatePath('/produtos'); revalidatePath('/admin/categorias'); return { success: true }; } catch (error) { return { error: error.message }; } }
export async function removeCategory(id) { try { const supabase = await admin(); const { error } = await supabase.from('categories').delete().eq('id', id); if (error) throw error; revalidatePath('/'); revalidatePath('/produtos'); revalidatePath('/admin/categorias'); return { success: true }; } catch (error) { return { error: error.message || 'Não foi possível excluir.' }; } }
