'use client';

import { LoaderCircle, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useMemo, useState } from 'react';
import { removeCategory, saveCategory, toggleCategory } from './actions';

const slugify = (value) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const inputClass = 'w-full rounded-xl border border-white/15 bg-black/30 px-4 py-3 text-sm text-white outline-none transition placeholder:text-zinc-600 focus:border-brand';

export default function CategoryManager({ initialCategories }) {
  const router = useRouter();
  const [categories, setCategories] = useState(initialCategories);
  const [editing, setEditing] = useState(null);
  const [query, setQuery] = useState('');
  const [notice, setNotice] = useState(null);
  const [busy, setBusy] = useState(false);
  const visible = useMemo(() => categories.filter((category) => category.name.toLowerCase().includes(query.toLowerCase())), [categories, query]);
  const current = editing || {};

  async function submit(event) { event.preventDefault(); setBusy(true); setNotice(null); const result = await saveCategory(new FormData(event.currentTarget)); setBusy(false); if (result.error) return setNotice({ error: result.error }); setEditing(null); setNotice({ success: 'Categoria salva com sucesso.' }); router.refresh(); }
  async function change(id, isActive) { setBusy(true); setNotice(null); const result = await toggleCategory(id, isActive); setBusy(false); if (result.error) return setNotice({ error: result.error }); setCategories((items) => items.map((item) => item.id === id ? { ...item, is_active: isActive } : item)); router.refresh(); }
  async function remove(id) { if (!window.confirm('Excluir esta categoria? Os produtos não serão apagados.')) return; setBusy(true); setNotice(null); const result = await removeCategory(id); setBusy(false); if (result.error) return setNotice({ error: result.error }); setCategories((items) => items.filter((item) => item.id !== id)); setNotice({ success: 'Categoria excluída com sucesso.' }); router.refresh(); }

  return <><div className="mt-8 flex flex-wrap items-center justify-between gap-4"><label className="relative w-full sm:max-w-sm"><span className="sr-only">Pesquisar categoria</span><Search size={17} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Pesquisar categoria" className={`${inputClass} pl-11`}/></label><button type="button" onClick={() => { setEditing({ is_active: true, sort_order: categories.length * 10 + 10 }); setNotice(null); }} className="button-primary"><Plus size={16}/>Nova categoria</button></div>
  {editing && <form onSubmit={submit} className="mt-6 grid gap-4 rounded-2xl border border-white/10 bg-white/[.025] p-5 sm:grid-cols-2"><div className="sm:col-span-2"><p className="eyebrow">{current.id ? 'Edição' : 'Nova categoria'}</p><h2 className="mt-2 text-xl font-extrabold">{current.id ? 'Editar categoria' : 'Adicionar categoria'}</h2></div><input type="hidden" name="id" value={current.id || ''}/><label className="grid gap-2 text-sm font-semibold">Nome<input name="name" required defaultValue={current.name || ''} onChange={(event) => { const slug = event.currentTarget.form.elements.slug; if (!current.id) slug.value = slugify(event.target.value); }} className={inputClass}/></label><label className="grid gap-2 text-sm font-semibold">Slug<input name="slug" required defaultValue={current.slug || ''} className={inputClass}/></label><label className="grid gap-2 text-sm font-semibold sm:col-span-2">Descrição<textarea name="description" defaultValue={current.description || ''} rows="3" className={inputClass}/></label><label className="grid gap-2 text-sm font-semibold">Ordem<input name="sortOrder" type="number" defaultValue={current.sort_order || 0} className={inputClass}/></label><label className="flex items-center gap-3 self-end rounded-xl border border-white/15 bg-black/20 px-4 py-3 text-sm font-semibold"><input name="isActive" type="checkbox" defaultChecked={current.is_active}/> Categoria ativa</label><label className="grid gap-2 text-sm font-semibold">Imagem<input name="image" type="file" accept="image/jpeg,image/png,image/webp" className="text-xs text-zinc-400 file:mr-3 file:rounded-lg file:border-0 file:bg-white/10 file:px-3 file:py-2 file:text-white"/></label><label className="grid gap-2 text-sm font-semibold">Banner opcional<input name="banner" type="file" accept="image/jpeg,image/png,image/webp" className="text-xs text-zinc-400 file:mr-3 file:rounded-lg file:border-0 file:bg-white/10 file:px-3 file:py-2 file:text-white"/></label><div className="flex gap-3 sm:col-span-2"><button disabled={busy} className="button-primary">{busy ? <><LoaderCircle size={16} className="animate-spin"/>Salvando...</> : 'Salvar categoria'}</button><button type="button" disabled={busy} onClick={() => setEditing(null)} className="button-dark">Cancelar</button></div></form>}
  {notice && <p role={notice.error ? 'alert' : 'status'} className={`mt-6 rounded-xl border px-4 py-3 text-sm ${notice.error ? 'border-red-400/30 bg-red-400/10 text-red-200' : 'border-emerald-400/30 bg-emerald-400/10 text-emerald-200'}`}>{notice.error || notice.success}</p>}
  <div className="mt-6 overflow-x-auto rounded-2xl border border-white/10"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-white/[.04] text-[11px] font-bold uppercase tracking-wider text-zinc-400"><tr><th className="px-5 py-4">Categoria</th><th className="px-5 py-4">Slug</th><th className="px-5 py-4">Ordem</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Ações</th></tr></thead><tbody>{visible.map((category) => <tr key={category.id} className="border-t border-white/10 transition hover:bg-white/[.025]"><td className="px-5 py-4 font-bold">{category.name}</td><td className="px-5 py-4 text-zinc-400">/{category.slug}</td><td className="px-5 py-4 text-zinc-400">{category.sort_order}</td><td className="px-5 py-4"><button disabled={busy} onClick={() => change(category.id, !category.is_active)} className={`rounded-full border px-3 py-1 text-xs font-bold ${category.is_active ? 'border-emerald-400/30 text-emerald-200' : 'border-white/15 text-zinc-500'}`}>{category.is_active ? 'Ativa' : 'Inativa'}</button></td><td className="px-5 py-4 text-right"><button type="button" onClick={() => { setEditing(category); setNotice(null); }} className="rounded-lg border border-white/15 p-2 text-zinc-200 transition hover:border-brand hover:text-brand" aria-label={`Editar ${category.name}`}><Pencil size={15}/></button><button type="button" disabled={busy} onClick={() => remove(category.id)} className="ml-2 rounded-lg border border-red-400/30 p-2 text-red-200 transition hover:bg-red-400/10" aria-label={`Excluir ${category.name}`}><Trash2 size={15}/></button></td></tr>)}</tbody></table>{!visible.length && <p className="px-5 py-10 text-center text-zinc-500">Nenhuma categoria encontrada.</p>}</div></>;
}
